apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: dev
spec:
  type: NodePort # Permet d'exposer le service sur un port de la VM
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 8888       # Port du service
      targetPort: 8888 # Port du conteneur (doit correspondre au deployment)
